spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #?? table?? #application.properties?? ?? ???.
      #?? : ?????? ?????, ?? table ? ???(??? ?? Entity??? ????(Entity Annotation? ??? ?? ?? ????) ?. -> DB? ?? ?? ? ??? ?? ???.), ????
    properties:
      hibernate:
        #        show_sql: true #??? application.properties?? ?????.
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug #hibernate sql??? debug? ??. -> jpa? ???? sql? ? ???.
    #show-sql?? ??
    #show-sql : system.out.println?? ???? ?
    #logging.level.org.hibernate.SQL : ??? ???? ? -> ??? ??. show-sql? ???? ??.
  org.hibernate.type: trace #?????? ??? ???? ????. #???? ? ????? ???, ??????? ??????. # ?? ??